export const TOTAL_PEOPLE_RESULT = 'TOTAL_PEOPLE_RESULT' 
export const TOTAL_PLANET_RESULT = 'TOTAL_PLANET_RESULT' 
export const TOTAL_MOVIES_RESULT = 'TOTAL_MOVIES_RESULT' 

export const MOVIE_CHARACTERS = 'MOVIE_CHARACTERS'
export const MOVIE_PLANETS = 'MOVIE_PLANETS'

export const PERSON_DETAIL = 'PERSON_DETAIL' 
